### ISSUE TITLE
миша клоун

### ISSUE THREAD

**Issue by SavokBS** [crossfireTeam/Offer-Backgrounds#1]
миша обиделся что я вернулся к хеону и кинул в чс и выгнал с кф. лошпед

**Comment by SavokBS** [comment]
не знаю что с тобой случилось... не ожидал от тебя такого...

**Comment by root-7325** [comment]
лошпед это тот кто открыл этот issue

**Comment by vanyadev228** [comment]
Че за хуйня

**Comment by Zhany4ka** [comment]
че
